version: '3'
services:
  web:
    build: ./src
    ports:
      - "80:80"
    volumes:
      - ./src/app:/app
      - ./data:/data
    entrypoint: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80